### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by Cazawaka** [DRNUMBER1/PostmanInstaller#1]
1. Who using postman in 2023?
2. Why you did it?
3. Why we need it?
4. How old are you?

**Comment by DRNUMBER1** [comment]
1.) Few people still use postman, I still use it.
2.) Srgantmoomoo had created an Installer for Postman but never finished it, so instead I did it. I made it for fun and for trying out new stuff.
3.) Installing Forge/Optifine/Baritone/Postman separately is time consuming, hence the installer does it with ease.
4.) 18.

**Comment by srgantmoomoo** [comment]
1.) Who cares?
2.) Why does it matter so much to you?
3.) Because recior is above all.
4.) 18.
5.) cope seethe.
